### ISSUE TITLE
Create model - Asset Inventory

### ISSUE THREAD

**Issue by redheadedrod** [redheadedrod/cis467-amp-cmms#6]
int: ID
string: Name
AssetType: assetTypeID
Location: locationID

Class with ID, Name of asset, link to asset type, location of asset (Multi layer capable, ie faucet can be on a sink, the sink can be in the bathroom, the bathroom can be the master bathroom, the master bathroom can be in the house, the house can be on a street, the street can be within a town etc..)

**Comment by benzino87** [comment]
Requires models: asset type and location

**Comment by benzino87** [comment]
Need to update model to contain an instance of AssetType and Location.
